---
title: "Text Analysis Notebook"
---

In this notebook we analyse the content of the tweets. We want to understand which are the main topics discussed and their corresponding development over time. 

## Prepare Notebook

```{r, warning=FALSE,  message=FALSE}
knitr::opts_knit$set(warning=FALSE, message=FALSE)

library(igraph)
library(magrittr)
library(lubridate)
library(tidytext)
library(tidyverse)
library(tm)
library(widyr)
library(wordcloud)

source(file = "../R/hashtags.R")
source(file = "../R/newtheme.R")
source(file = "../R/text_cleaning.R")
```

## Read Data

```{r, read data}
tweets_text_df <- readRDS(file = "../data/tweets_text_df.rds")
hashtags_count_df <- readRDS(file = "../data/hashtags_count.rds")
```

## Hashtags

In the data gathering phase we tracked the following hashtags:

```{r}
twitter_terms <- c(
  "21N", 
  "#21N", 
  "#21NSomosTodos",
  "#Paro21N", 
  "#YoMarchoEste21",
  "#YoMarchoEl21",
  "#YoNoMarchoEste21",
  "#YoNoMarchoEl21",
  "#RazonesParaMarchar",
  "#RazonesParaNoMarchar",
  "#100RazonesParaMarchar", 
  "#100RazonesParaNoMarchar", 
  "#YoNoParo",
  "#YoParoEl21NSinMiedo", 
  "#Cacerolazo", 
  "#22N", 
  "#23N",
  "#ToqueDeQueda"
)
```

Let us see the top hastags appearing ini the data:

```{r, fig.align="center"}
normalized_twitter_terms <- twitter_terms %>% 
  str_to_lower() %>% 
  str_remove_all(pattern = "#")

hashtags_count_df %>% 
  mutate(is_tracked = hashtag %in% normalized_twitter_terms) %>% 
  mutate(n = n /sum(n)) %>% 
  top_n(n = 30, wt = n) %>% 
  mutate(hashtag = reorder(hashtag, n)) %>%
  ggmyplot(aes(x = hashtag, y = n, fill = is_tracked)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
ggtitle(label = "Top Hashtags Count (Share)") 
```

```{r, fig.align="center"}
tweets_text_df %>% 
  count(created_at_round_hour) %>% 
  ggmyplot(mapping = aes(x = created_at_round_hour, y = n)) +
  geom_line(color = PALETTE_SET1[2])
```

```{r, fig.align="center"}
tweets_text_df %>% 
  count(created_at_round_hour, is_retweet) %>% 
  ggmyplot(mapping = aes(x = created_at_round_hour, y = n, color = is_retweet)) +
  geom_line()
```




